### ISSUE TITLE
Remove absolute URLs, change all URLs to relative ones

### ISSUE THREAD

**Issue by icyflame** [students-alumni-cell-iitkgp/mentorship-portal-php#13]
This will avoid problems like [this](https://github.com/students-alumni-cell-iitkgp/mentorship-portal-php/commit/b9f2ceef29b8a25ac1cafc6d0d49098e317d3e6d), and the main WWW issue in the first place would have been avoided if you had used relative URLs.

So, change everything to relative:

`www.mentorship.iitkgp.ernet.in/index.php` -> `/index.php`

**Comment by icyflame** [comment]
ping @uagarwal744 @punit121

**Comment by punit121** [comment]
base url changed @icyflame @uagarwal744
