### ISSUE TITLE
Backend not working

### ISSUE THREAD

**Issue by uagarwal744** [students-alumni-cell-iitkgp/mentorship-portal-php#7]
@punit121 Try fixing the backend part, form submission is showing error

**Comment by icyflame** [comment]
What was the problem?

**Comment by uagarwal744** [comment]
@icyflame earlier it was redirecting to wrong address, now fixed
I tried filling the form and details were successfully saved to the database

**Comment by icyflame** [comment]
@uagarwal744 and @punit121  :+1: 

Check out the other issues that I have just opened. And start fixing the frontend.
